---
version: '3.8'
services:
  octez-node:
    container_name: octez-node
    image: tezos/tezos-bare:master
    ports:
      - 8732:8732
      - 9932:9932
    networks:
      - datanetwork
    environment:
      TZNETWORK: ${TZNETWORK:-ghostnet}
    volumes:
      - $PWD/data:/home/tezos/data
    command: /usr/local/bin/octez-node run --rpc-addr=0.0.0.0:8732 --metrics-addr=0.0.0.0:9932 --data-dir=/home/tezos/data/node --network ${TZNETWORK} --allow-all-rpc 0.0.0.0


  smart-rollup-node:
    container_name: rollup-node
    image: tezos/tezos:master
    restart: always
    ports:
      - 8545:4545
      - 9933:9932
    environment:
      SOR_ALIAS_OR_ADDR: ${SOR_ALIAS_OR_ADDR}
      OPERATOR_ADDR: ${OPERATOR_ADDR}
      ROLLUP_NODE_MODE: ${ROLLUP_NODE_MODE:-observer}
      client_dir: /home/tezos/data/client
      smart_rollup_node_data_dir: /home/tezos/data/smartrollup
      NODE_HOST: octez-node
      NODE_RPC_PORT: 8732
    networks:
      - datanetwork
    command: octez-smart-rollup-node run ${ROLLUP_NODE_MODE} for ${SOR_ALIAS_OR_ADDR} with operators ${OPERATOR_ADDR} --rpc-addr 0.0.0.0 --metrics-addr 0.0.0.0:9932 --rpc-port 4545 --log-kernel-debug
    volumes:
      - $PWD/data:/home/tezos/data

networks:
  datanetwork:
    driver: bridge
    name: datanetwork