# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "consensus-node"
version = "0.1.0"
license = "MIT"
authors = ["TriliTech <contact@trili.tech>"]
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "consensus-node"
path = "src/main.rs"