[package]
name = "risc-v-dummy"
version = "0.0.0"
edition = "2021"

[target.'cfg(target_os = "hermit")'.dependencies.hermit]
git = "https://github.com/victor-dumitrescu/hermit-rs.git"
default-features = false

[dependencies.riscv-rt]
version = "*"
optional = true

[dependencies.tezos_crypto_rs]
git = "https://github.com/victor-dumitrescu/tezedge.git"
default-features = false
optional = true

[dependencies.tezos-smart-rollup-panic-hook]
path = "../../kernel_sdk/panic-hook"
version = "0.2.1"
default-features = false

[dependencies.tezos-smart-rollup]
path = "../../kernel_sdk/sdk"
version = "0.2.1"
default-features = false
features = ["debug_alloc", "proto-alpha-no-mock"]

[features]
default = ["bare-metal"]
bare-metal = ["riscv-rt"]
crypto = ["tezos_crypto_rs"]
