[package]
name = "risc-v-dummy"
version = "0.0.0"
edition = "2021"

[dependencies.riscv-rt]
version = "*"
optional = true

[dependencies.tezos-smart-rollup-core]
path = "../../kernel_sdk/core"
version = "0.2.1"
default-features = false
features = ["proto-alpha"]

[dependencies.tezos-smart-rollup-panic-hook]
path = "../../kernel_sdk/panic-hook"
version = "0.2.1"
default-features = false

[features]
default = ["bare-metal"]
bare-metal = ["riscv-rt"]
libc = ["tezos-smart-rollup-core/libc"]
