# Basic configuration to guard against double-pipelines
workflow:
  rules:
    # Allow 'Before merging' pipelines
    - if: '$CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    # Disallow all other pipelines
    - when: never


include:
  -  local: not_arvid.yml
     rules:
      - if: '$GITLAB_USER_LOGIN != "arvidnl"'
  -  local: arvid.yml
     rules:
      - if: '$GITLAB_USER_LOGIN == "arvidnl"'
