---

# General setup
default:
  interruptible: true

variables:
  # /!\ CI_REGISTRY is overriden to use a private Docker registry mirror in AWS ECR
  # in GitLab namespaces `nomadic-labs` and `tezos`
  ## This value MUST be the same as `opam_repository_tag` in `scripts/version.sh`
  foo: "NOT BAR"

workflow:
  name: "[$PIPELINE_TYPE] $CI_COMMIT_TITLE"
  rules:
    # /!\ These rules should be mutually exclusive and kept in sync
    # with the corresponding 'if'-rules on the pipeline includes
    # below.

    - if: '$foo == "BAR"'
      variables:
        PIPELINE_TYPE: 'foo is bar'
    - if: '$foo != "BAR"'
      variables:
        PIPELINE_TYPE: 'foo is not bar'

tezt:
  image: alpine
  script:
  - echo "I run ($PIPELINE_TYPE)"
