---
default:
  interruptible: true
workflow:
  name: "[$PIPELINE_TYPE] $CI_COMMIT_TITLE"
  rules:
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PIPELINE_TYPE: before_merging
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "latest-release"
      variables:
        PIPELINE_TYPE: latest_release
    - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "latest-release-test"
      variables:
        PIPELINE_TYPE: latest_release_test
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
      variables:
        PIPELINE_TYPE: master_branch
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+(?:\-rc\d+)?$/
      variables:
        PIPELINE_TYPE: release_tag
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+\-beta\d*$/
      variables:
        PIPELINE_TYPE: beta_release_tag
    - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
      variables:
        PIPELINE_TYPE: release_tag_test
    - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null && $CI_COMMIT_TAG !~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
      variables:
        PIPELINE_TYPE: non_release_tag
    - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null && $CI_COMMIT_TAG !~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
      variables:
        PIPELINE_TYPE: non_release_tag_test
    - if: $CI_PIPELINE_SOURCE == "schedule" && $TZ_SCHEDULE_KIND == "EXTENDED_TESTS"
      variables:
        PIPELINE_TYPE: schedule_extended_tests
    - when: never
variables:
  build_deps_image_version: f84b4412bf92f81fa4d554aed624fa0a6a72ec96
  build_deps_image_name: "${CI_REGISTRY}/tezos/opam-repository"
  GIT_STRATEGY: fetch
  GIT_DEPTH: "1"
  GET_SOURCES_ATTEMPTS: "2"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "2"
  OPAMRETRIES: "5"
  FF_USE_FASTZIP: "true"
  RUNTEZTALIAS: "false"
.image_template__runtime_e2etest_dependencies:
  image: ${build_deps_image_name}:runtime-e2etest-dependencies--${build_deps_image_version}
.image_template__runtime_build_test_dependencies:
  image: ${build_deps_image_name}:runtime-build-test-dependencies--${build_deps_image_version}
.image_template__runtime_build_dependencies:
  image: ${build_deps_image_name}:runtime-build-dependencies--${build_deps_image_version}
.image_template__runtime_prebuild_dependencies:
  image: ${build_deps_image_name}:runtime-prebuild-dependencies--${build_deps_image_version}
.image_template__rust_toolchain:
  image: ${build_deps_image_name}:rust-toolchain--${build_deps_image_version}
.image_template__docker:
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.6.0"
.image_template__alpine:
  image: alpine:3.18
stages:
  - trigger
  - sanity
  - build
  - test
  - test_coverage
  - packaging
  - doc
  - prepare_release
  - publish_release_gitlab
  - publish_release
  - publish_package_gitlab
  - manual
trigger:
  extends:
    - .default_settings_template
    - .image_template__alpine
  stage: trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_NAMESPACE == "tezos" && $CI_MERGE_REQUEST_ASSIGNEES !~ /nomadic-margebot/
      when: manual
    - when: always
  allow_failure: false
  timeout: "10m"
  script:
    - echo Trigger pipeline 🤠
    - ./scripts/ci/check_alpine_version.sh
include:
  - local: .gitlab/ci/jobs/shared/templates.yml
  - local: .gitlab/ci/pipelines/before_merging.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "merge_request_event"
  - local: .gitlab/ci/pipelines/latest_release.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "latest-release"
  - local: .gitlab/ci/pipelines/latest_release_test.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "latest-release-test"
  - local: .gitlab/ci/pipelines/master_branch.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  - local: .gitlab/ci/pipelines/release_tag.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+(?:\-rc\d+)?$/
  - local: .gitlab/ci/pipelines/beta_release_tag.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+\-beta\d*$/
  - local: .gitlab/ci/pipelines/release_tag_test.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
  - local: .gitlab/ci/pipelines/non_release_tag.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE == "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null && $CI_COMMIT_TAG !~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
  - local: .gitlab/ci/pipelines/non_release_tag_test.yml
    rules:
      - if: $CI_PROJECT_NAMESPACE != "tezos" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null && $CI_COMMIT_TAG !~ /^v\d+\.\d+(?:\-(rc|beta)\d*)?$/
  - local: .gitlab/ci/pipelines/schedule_extended_test.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule" && $TZ_SCHEDULE_KIND == "EXTENDED_TESTS"
