# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-core"
publish = false
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
bcs = { workspace = true }
thiserror = { workspace = true }
