# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-node"
publish = false
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# DSN
dsn-client = { workspace = true }
dsn-core = { workspace = true }

# Protocols
loopback = { workspace = true }

[[bin]]
name = "dsn-node"
path = "src/main.rs"