# SPDX-FileCopyrightText: 2023 Functori <contact@functori.com>
#
# SPDX-License-Identifier: MIT

[package]
name = 'evm_evaluation'
version = '0.1.0'
edition = '2021'
license = "MIT"

[dependencies]
thiserror.workspace = true
evm-execution.workspace = true
tezos_ethereum.workspace = true
tezos-smart-rollup-mock.workspace = true
hex.workspace = true
hex-literal.workspace = true

bytes = "1.5"
walkdir = "2.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
# Overwriting primitive-types from workspace to enable multiple features
primitive-types = { version = "0.12.1", features = ["rlp", "serde"] }
primitives = { package = "revm-primitives", version = "1.1.2", features = [
    "serde",
] }
# wasm32-unknown-unknown target is not supported by default
# the following line is needed for the current workspace 
getrandom = { version = "0.2", features = ["js"] }
