# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
  # Kernel Dev
  "tezos_smart_rollup_core",
  "tezos_smart_rollup_host",
  "tezos_smart_rollup_debug",
  "tezos_smart_rollup_mock",
  "tezos_smart_rollup_encoding",
  "tezos_smart_rollup_storage",
  "tezos_smart_rollup_panic_hook",
  "tezos_smart_rollup_entrypoint",
  # UX
  "installer_kernel",
  "installer_client",
  "installer_config",
]
