# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-transaction"
publish = false
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
