[workspace]
resolver = "2"
members = [
  # Libraries
  "kernel_loader",
  "machine_state",
  "interpreter",
  "pvm",
  "parser",
  # Executables
  "sandbox",
]
exclude = ["jstz", "dummy_kernel", "tests"]
