# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-host"
edition = "2021"
version = "0.2.1"
license = "MIT"
authors = ["TriliTech <contact@trili.tech>"]
repository = "https://gitlab.com/tezos/tezos.git"
description = "Safe Runtime trait for Tezos Smart Rollups host functions."
keywords = ["tezos", "smart", "rollup"]
categories = ["no-std", "no-std::no-alloc", "api-bindings", "wasm"]

[dependencies.tezos-smart-rollup-core]
path = "../core"
version = "0.2.1"

[dependencies.tezos_crypto_rs]
git = "https://github.com/victor-dumitrescu/tezedge.git"
default-features = false
optional = true

[dependencies.tezos_data_encoding]
git = "https://github.com/victor-dumitrescu/tezedge.git"
optional = true

[dependencies.thiserror]
version = "1.0"
optional = true

[dependencies.mockall]
version = "0.11.0"
optional = true

[features]
default = ["alloc", "crypto"]
crypto = ["tezos_crypto_rs"]
alloc = ["thiserror", "tezos_data_encoding"]
testing = ["crypto", "mockall", "tezos-smart-rollup-core/testing"]
proto-nairobi = ["tezos-smart-rollup-core/proto-nairobi"]
proto-alpha = ["tezos-smart-rollup-core/proto-alpha"]
# Required for 'impl Error for RuntimeError'
std = []
