octogram_binary:
  push: octogram

agents:
  - name: node
    address: 127.0.0.1
    user: root
    port: 30000
    identity: ~/.ssh/tf

  - name: localhost
    address: 127.0.0.1
    user: root
    port: 30000
    identity: ~/.ssh/tf

vars:
  network: sandbox
  
stages:
  - name: Initialize protocol file
    with_agents: 'localhost'
    run_agents: concurrent
    jobs:
      - name: Upload protocol file
        copy:
          local_path: 'src/proto_alpha/parameters/{{ vars.network }}-parameters.json'          
          remote_path: '.'

      - name: Start HTTP server
        builtins.start_http_server:
          http_port: '30999'

  - name: Running nodes
    with_agents: 'node'
    run_agents: concurrent
    jobs:
      - name: Push file
        builtins.prefetch: 'localhost://sandbox-parameters.json'

      - name: Upload octez-node
        run_items: concurrent
        copy:
          local_path: '{{ item }}'
          remote_path: '.'
        with_items:
          - octez-node
          - octez-client
 
      - name: Upload octez-client
        copy:
          local_path: octez-client
          remote_path: '.'
        
      - name: Start octez-node
        tezos.start_node:
          name: node
          path_node: self://./octez-node
          network: '{{ vars.network }}'
          synchronization_threshold: 0
          rpc_port: '30001'
          metrics_port: '30002'
          net_port: '30003'
          
      - name: Activate protocol
        tezos.activate_protocol:
          endpoint: self://node
          path_client: self://./octez-client
          protocol: alpha
          parameter_file: 'self://sandbox-parameters.json'
          
      - name: Wait for bootstrapped node
        tezos.wait_for_bootstrapped:
          path_client: self://./octez-client
          endpoint: self://node
