# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = 'evm_mockup_kernel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies]
kernel = { git = "https://gitlab.com/tezos/kernel", branch = "main", default-features = false }
host = { git = "https://gitlab.com/tezos/kernel", branch = "main"  }
debug = { git = "https://gitlab.com/tezos/kernel", branch = "main" }
mock_runtime = { git = "https://gitlab.com/tezos/kernel", branch = "main", default-features = false }

num-bigint = "0.3"
rlp = "0.5.2"
hex = "0.4.3" # This crate is only for debugging and inserting hex encoded transactions, and will be removed
