# SPDX-FileCopyrightText: 2024 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "dsn-api"
publish = false
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

# DSN primitives
dsn-transaction = { workspace = true }
dsn-pre-block = { workspace = true }
