# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
  "kernel",
  "collector",
]

[workspace.dependencies]
tezos-smart-rollup-core = { path = "../kernel_sdk/core" }
tezos-smart-rollup-host = { path = "../kernel_sdk/host" }
tezos-smart-rollup-debug = { path = "../kernel_sdk/debug" }
tezos-smart-rollup-entrypoint = { path = "../kernel_sdk/entrypoint" }
tezos-smart-rollup-storage = { path = "../kernel_sdk/storage" }
tezos-smart-rollup-encoding = { path = "../kernel_sdk/encoding" }
tezos-smart-rollup-mock = { path = "../kernel_sdk/mock" }

[patch.crates-io]
tezos_crypto_rs = { git = "https://github.com/trilitech/tezedge.git", branch = "emturner@tz1-hash-before-signing" }