---
version: '3.8'
services:

  _tezos_with_curl_build:
    container_name: tezos_with_curl_build
    image: tezos_with_curl:${OCTEZ_TAG}
    logging:
      driver: "json-file"
    command: ['echo', 'build completed']  # any linux command which directly terminates.
    build:
      context: $PWD/tezos_with_curl
      dockerfile: $PWD/tezos_with_curl/Dockerfile
      args:
        OCTEZ_TAG: ${OCTEZ_TAG}

  octez-node:
    container_name: octez-node
    depends_on:
      - _tezos_with_curl_build
    image: tezos_with_curl:${OCTEZ_TAG}
    logging:
      driver: "json-file"
    healthcheck:
      test: curl http://0.0.0.0:8732/monitor/bootstrapped
    volumes:
      - ${HOST_TEZOS_DATA_DIR}:/home/tezos
    networks:
      - etherlink-net
    ports:
      - 8732:8732
    entrypoint: /usr/local/bin/octez-node
    command: run --rpc-addr=0.0.0.0:8732 --allow-all-rpc 0.0.0.0

  smart-rollup-node:
    container_name: rollup-node
    image: tezos_with_curl:${OCTEZ_TAG}
    logging:
      driver: "json-file"
    depends_on:
      _tezos_with_curl_build:
        condition: service_completed_successfully
      octez-node:
        condition: service_healthy
    restart: always
    volumes:
      - ${HOST_TEZOS_DATA_DIR}:/home/tezos
    ports:
      - 8733:8733
    networks:
      - etherlink-net
    healthcheck:
      test: curl http://0.0.0.0:8733/global/smart_rollup_address
    entrypoint: /usr/local/bin/octez-smart-rollup-node
    command: --endpoint http://octez-node:8732 run

  sequencer:
    container_name: evm-sequencer
    image: tezos/tezos-bare:${OCTEZ_TAG}
    logging:
      driver: "json-file"
    depends_on:
      smart-rollup-node:
        condition: service_healthy
    restart: always
    volumes:
      - ${HOST_TEZOS_DATA_DIR}:/home/tezos
    networks:
      - etherlink-net
    ports:
      - 8545:8545
    entrypoint: /usr/local/bin/octez-evm-node
    command: run sequencer with endpoint http://rollup-node:8733 signing with ${SEQUENCER_SECRET_KEY} --rpc-addr 0.0.0.0 --rpc-port 8545 --initial-kernel /home/tezos/kernel/sequencer.wasm --preimage-dir /home/tezos/kernel/_evm_installer_preimages --time-between-blocks 10 --cors-origins '*' --cors-headers '*'

  blockscout-redis-db:
    image: 'redis:alpine'
    container_name: blockscout-redis-db
    logging:
      driver: "json-file"
    expose:
      - 6379
    command: redis-server
    networks:
      - blockscout-net

  blockscout-db:
    image: postgres:14
    container_name: blockscout-db
    logging:
      driver: "json-file"
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    networks:
      - blockscout-net

  blockscout:
    depends_on:
      - blockscout-db
      - blockscout-redis-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    logging:
      driver: "json-file"
    container_name: blockscout
    restart: always
    stop_grace_period: 5m
    links:
      - blockscout-db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./blockscout.env
    environment:
      SUBNETWORK: Etherlink
      CHAIN_ID: ${EVM_CHAIN_ID}
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true
      MICROSERVICE_SC_VERIFIER_ENABLED: false
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: false
      MICROSERVICE_SIG_PROVIDER_ENABLED: false
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ACCOUNT_REDIS_URL: redis://blockscout-redis-db:6379
    ports:
      - 4000:4000
    networks:
      - etherlink-net
      - blockscout-net


networks:
  etherlink-net:
  blockscout-net:
